# name: Merge on main
# on:
#   pull_request:
#     branches:
#       - main
#     types: [closed]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14.x]
#     steps:
#       - name: Checkout Code
#         if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
#         uses: actions/checkout@v2

#       - name: Fetch other branches
#         if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
#         run: git fetch --no-tags --prune --depth=5 origin main

#       - name: Use Node.js ${{ matrix.node-version }}
#         if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install environment
#         if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
#         run: npm ci

#       - name: Run lint
#         run: ./.github/scripts/run-linting.sh True

#       - name: Tests coverage
#         run: ./.github/scripts/run-testing.sh True

#       - name: SonarCloud Scan
#         uses: sonarsource/sonarcloud-github-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.ACTION_AUTH_TOKEN }}
#           SONAR_TOKEN: ${{ secrets.SONAR_AUTH_TOKEN }}

#       - name: Deploy
#         if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
#         env:
#           NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
#         run: |
#           npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
#           ./.github/scripts/publish-libraries.sh

#       - name: Build Docs
#         if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
#         run: ./.github/scripts/build-docs.sh

#       - name: Commit files
#         if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git add .
#           git commit -m "Release [skip-ci]" -a || true

#       - name: Push changes
#         if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.ACTION_AUTH_TOKEN }}
#           tags: true
#           force: true
